// <auto-generated />
namespace EDO.Data.EFModelCommon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class UserBusinessPositionFix3Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserBusinessPositionFix3Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201311151423149_UserBusinessPositionFix3Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
